### ISSUE TITLE
Number.isNaN is not supported in IE 9-10 and some other older browsers

### ISSUE THREAD

**Issue by arturi** [Flet/prettier-bytes#3]
Hi, thanks for this module! We’ve run into an issue of older versions of IE (11<) choking [on this](https://github.com/Flet/prettier-bytes/blob/master/index.js#L4), because they don’t support Number.isNaN.

Could plain old isNaN() be used here? Also, a polyfill exists https://github.com/leonderijke/Number.isNaN, but seems weird to add it for this tiny thing.

Thanks.

**Comment by ungoldman** [comment]
Seems totally reasonable to me to use the older [`isNaN()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/isNaN) function.

**Comment by Flet** [comment]
Fixed in #4 

published as `prettier-bytes@1.0.4`
