### ISSUE TITLE
Change "KB" back to "kB"

### ISSUE THREAD

**Issue by getsnoopy** [Flet/prettier-bytes#5]
Please change _KB_ back to the official symbol _kB_; _KB_ is not "more pretty" than _kB_. The usual way that someone can figure out whether the bytes being displayed are using the proper 1000-base or if they're a 1024-base is by looking at whether the proper symbol for the prefix _kilo-_ is being used.

I was surprised to find that this package uses the proper 1000-base, but misuses the symbol for the prefix. The SI (modern metric system) symbols are not merely ornamental, but are semantic. _k_ means _kilo-_, while _K_ means _kelvin_. This is not to mention that all operating systems except for Windows have fixed this historical mix-up by switching to the proper SI definitions, so they'd see "kB" on their computers rather than "KB". The issue is complicated enough as it is, but it seems like this is an entirely unnecessary reason to complicate it further.

**Comment by Flet** [comment]
Hello!

Thanks for the feedback! You're point is correct and well-taken.

You may be interested in the "less pretty" but more accurate package by Sindre: https://github.com/sindresorhus/pretty-bytes

Some other relevant references to this:
https://github.com/sindresorhus/pretty-bytes/issues/17
https://github.com/sindresorhus/pretty-bytes/pull/5

https://github.com/Flet/prettier-bytes/pull/1

Again, I appreciate the feedback! It sounds like `pretty-bytes` may be a good alternative to pursue.
